CREATE TABLE USERS
(
USER_ID INT NOT NULL PRIMARY KEY,
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
PHONE_NUMBER CHAR(255) UNIQUE,
EMAIL_ADDRESS VARCHAR(255),
GENDER NVARCHAR(10),
PRODUCT_ID INT
);

CREATE TABLE PRODUCTS
(
PRODUCT_ID INT NOT NULL PRIMARY KEY,
PRODUCT_NAME VARCHAR(100) NOT NULL,
PRODUCT_AMOUNT VARCHAR(100) NOT NULL,
PRODUCT_CATEGORY VARCHAR(100)
);

CREATE TABLE DELIVERY
(STAFF_ID INT NOT NULL PRIMARY KEY,
PRODUCT_NAME VARCHAR(100) NOT NULL,
QUANTITY INT NOT NULL,
STAFF_NAME VARCHAR(100) NOT NULL,
DELIVERY_CITY VARCHAR(255) NOT NULL,
PRODUCT_AMOUNT VARCHAR(100) NOT NULL
);

ALTER TABLE USERS
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID);

DROP TABLE USERS;




INSERT INTO PRODUCTS
VALUES (001, 'JOHNSOAP', '100', 'BABIES');

INSERT INTO PRODUCTS
VALUES (002, 'beef', '1000', 'MEAT');

INSERT INTO PRODUCTS
VALUES (003, 'MAGGI', '500', 'GROCERY');

SELECT * FROM PRODUCTS;

INSERT INTO DELIVERY
VALUES (201, 'MAGGI', 10, 'ELI', 'NSUKKA', '500');

INSERT INTO DELIVERY
VALUES (202, 'BEEF', 2, 'JOHN', 'ABUJA', '1000');


